CREATE TABLE spk_insurans (
    insurans_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kontrak_id NUMBER,
    jenis_insurans VARCHAR2(10),
    nama_bank VARCHAR2(255),
    no_polisi VARCHAR2(50),
    tempoh_dlp NUMBER(11),
    jumlah_insurans NUMBER(15,2),
    tarikh_mula DATE,
    tarikh_akhir DATE,
    status VARCHAR2(9),
    tarikh_asal DATE,
    tarikh_lanjutan DATE,
    insurans_file BLOB,
    CONSTRAINT fk_insurans FOREIGN KEY (kontrak_id) REFERENCES spk_kontrak(id),
    CONSTRAINT chk_jenis_insurans CHECK (jenis_insurans IN ('', 'workmen', 'car', 'public', 'socso', 'iow')),
    CONSTRAINT chk_ti CHECK (status IN ('', 'asal', 'lanjutan'))
);
