CREATE TABLE spk_bon (
    bon_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kontrak_id NUMBER,
    jenis_bon VARCHAR2(12),
    no_jaminan VARCHAR2(50),
    jumlah NUMBER(15,2),
    tarikh_mula DATE,
    tarikh_akhir DATE,
    status VARCHAR2(9),
    tarikh_asal DATE,
    tarikh_lanjutan DATE,
    bon_file BLOB,
    CONSTRAINT fk_bon FOREIGN KEY (kontrak_id) REFERENCES spk_kontrak(id),
    CONSTRAINT chk_jenis_bon CHECK (jenis_bon IN ('', 'performance', 'wjp')),
    CONSTRAINT chk_tb CHECK (status IN ('', 'asal', 'lanjutan'))
);
