CREATE TABLE spk_projek (
    projek_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_projek VARCHAR2(255) NOT NULL,
    nama_pemohon VARCHAR2(255) NOT NULL,
    no_kontrak VARCHAR2(100),
    jenis_kontrak VARCHAR2(20),
    anggaran_kos NUMBER(15,2),
    tahun NUMBER(4),
    sumber_peruntukan VARCHAR2(20),
    status_projek VARCHAR2(20) DEFAULT 'perancangan' NOT NULL,
    reg_date DATE DEFAULT CURRENT_DATE,
    CONSTRAINT chk_jenis_kontrak CHECK (jenis_kontrak IN ('', 'perkhidmatan', 'bekalan', 'kerja')),
    CONSTRAINT chk_sumber_peruntukan CHECK (sumber_peruntukan IN ('', 'd.e', 'mengurus', 'lain-lain')),
    CONSTRAINT chk_status_projek CHECK (status_projek IN ('perancangan', 'aktif', 'kiv'))
);

-- Sequence untuk table PROJEK
CREATE SEQUENCE SPK_PROJEK_SEQ START WITH 1 INCREMENT BY 1;

-- Trigger untuk auto-generate ID dalam table PROJEK
CREATE OR REPLACE TRIGGER SPK_PROJEK_TRG 
BEFORE INSERT ON SPK_PROJEK 
FOR EACH ROW 
BEGIN 
    SELECT SPK_PROJEK_SEQ.NEXTVAL INTO :NEW.PROJEK_ID FROM DUAL;
END;
/