CREATE TABLE spk_kontraktor (
    kontraktor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_syarikat VARCHAR2(255),
    alamat CLOB,
    no_syarikat VARCHAR2(50),
    no_phone VARCHAR2(15),
    no_fax VARCHAR2(15),
    jenis_kontraktor VARCHAR2(15),
    spc BLOB,
    sst BLOB,
    CONSTRAINT chk_jenis_kontraktor CHECK (jenis_kontraktor IN ('', 'utama', 'subkontraktor'))
);
