CREATE TABLE spk_perolehan (
    perolehan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projek_id NUMBER,
    keputusan VARCHAR2(15),
    jenis_perolehan VARCHAR2(10),
    jenis_projek VARCHAR2(10),
    lukisan_tender NUMBER(1) DEFAULT 0,
    lukisan_tender_file BLOB,
    dokumen_meja_tender BLOB,
    ro_pindaan BLOB,
    kertas_kerja BLOB,
    borang_47a_47b BLOB,
    tapak BLOB,
    pelan_projek BLOB,
    kuantiti BLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_projek_id FOREIGN KEY (projek_id) REFERENCES spk_projek(projek_id),
    CONSTRAINT chk_keputusan CHECK (keputusan IN ('', 'lulus', 'lulus bersyarat', 'ditolak')),
    CONSTRAINT chk_jenis_perolehan CHECK (jenis_perolehan IN ('', 'sebutharga', 'tender', 'rfp')),
    CONSTRAINT chk_jenis_projek CHECK (jenis_projek IN ('', 'one-off', 'berkala'))
);

CREATE OR REPLACE TRIGGER trg_update_timestamp
BEFORE UPDATE ON spk_perolehan
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Sequence untuk table PEROLEHAN
CREATE SEQUENCE SPK_PEROLEHAN_SEQ START WITH 1 INCREMENT BY 1;

-- Trigger untuk auto-generate ID dalam table PEROLEHAN
CREATE OR REPLACE TRIGGER SPK_PEROLEHAN_TRG 
BEFORE INSERT ON SPK_PEROLEHAN 
FOR EACH ROW 
BEGIN 
    SELECT SPK_PEROLEHAN_SEQ.NEXTVAL INTO :NEW.PEROLEHAN_ID FROM DUAL;
END;
/