CREATE TABLE spk_kontrak (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projek_id NUMBER NOT NULL,
    kontraktor_id NUMBER NOT NULL,
    harga NUMBER(15,2),
    blr NUMBER(5,2),
    lad NUMBER(15,2),
    t_mula DATE,
    t_akhir DATE,
    CONSTRAINT kontrak_projek FOREIGN KEY (projek_id) REFERENCES spk_projek(projek_id),
    CONSTRAINT kontrak_kontraktor FOREIGN KEY (kontraktor_id) REFERENCES spk_kontraktor(kontraktor_id)
);